### PR TITLE
convert more old settings to their new name / value

### PR DESCRIPTION
**Pull request by BuBuaBu**

### CODE REVIEW

**Review by ubitux — COMMENTED** [review]
Why do you need this? Are you trying to run the script with python2? I believe you're going to have other problems if you do so.

**Review by ubitux — COMMENTED** [review]
So, if we trust this, we end up with the following settings:

```
raft_margin: 15 -> 5
raft_surface_line_spacing: 0.4 -> 3.0
raft_interface_line_spacing: 0.9 -> 3.0
raft_base_line_spacing: 1.6 -> 3.0
raft_base_line_width: 0.8 -> 1.0
raft_interface_thickness: 0.15 -> 0.27
raft_interface_line_width: 0.7 -> 0.4
raft_airgap: 0.3 -> 0.22
```

These line spacing changes look pretty huge to me. Let's hope they're correct. Did you test it?

BTW, in the `fdmprinter.def.json` reference, they use both `value` and `default_value`. I was under the impression that `value` was just supposed to be an `eval()` version of `default_value`, but both seems to be in use.

So far I have assumed `default_value` was taking over but I might have been wrong.

Anyway, if we look at the `value` field of the 3 settings you're changing, we have:
- `raft_surface_line_spacing` = `raft_surface_line_width`
- `raft_interface_line_spacing` = `raft_interface_line_width + 0.2`
- `raft_base_line_spacing` = `raft_base_line_width * 2`

It may be interesting to try to analyze the meaning of these "defaults".

**Review by ubitux — APPROVED** [review]

**Review by ubitux — COMMENTED** [review]
Just a small comment on this one: comment should be the original field, `fill_overlap`, not `infill_overlap`.

**Comment by ubitux** [comment]
dammit, github doesn't allow you to comment on single commit? the fuck is this.

**Comment by BuBuaBu** [comment]
- removed encoding line. Python2 issue ^^. What version do you use? cause all generated json do not have same keys order.
- Fixed `infill_overlap` comment

**Comment by BuBuaBu** [comment]
Concerning `raft_*_line_spacing`, I will run some test print tomorrow.
But actually if we want to keep cbd behavior this is what it should be.

**Comment by ubitux** [comment]
I merged the branch as is, with a bunch of other commits on top. I hacked something about the material ø issue, so it is now usable out of the box.

I'm using Python 3.6 BTW. I thought Python decided to actually have ordered dict builtin (without a different odict type) but maybe I'm wrong. I'll look into this to force the ordered mode.

**Comment by BuBuaBu** [comment]
I made a confusion between raft and support...

Actually, their is no way (from gui) with CbD to get a raft. So no way to compare CbD raft settings with Cura 2.4.


To understand raft, I read this article: https://www.simplify3d.com/support/articles/rafts-skirts-and-brims/

**Comment by ubitux** [comment]
Should we drop all raft settings and rely on the default?

That article seems to say that ABS is the main use-case for rafts; in CbD, if you add an ABS material, wouldn't that lead to its usage?

**Pull request merged**
